/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "SXYKT.h"
/* Header for class ebeijia_android_com_ndk_jni_MyNDK */

#ifndef _Included_ebeijia_android_com_ndk_jni_MyNDK
#define _Included_ebeijia_android_com_ndk_jni_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ebeijia_android_com_ndk_jni_MyNDK
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jstring JNICALL Java_ebeijia_android_com_ndk_1jni_MyNDK_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
