/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ebeijia_util_Constant */

#ifndef _Included_com_android_ebeijia_util_Constant
#define _Included_com_android_ebeijia_util_Constant
#ifdef __cplusplus
extern "C" {
#endif
#undef com_android_ebeijia_util_Constant_DelayedTime
#define com_android_ebeijia_util_Constant_DelayedTime 100L
/*
 * Class:     com_android_ebeijia_util_Constant
 * Method:    baseUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ebeijia_util_Constant_baseUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_android_ebeijia_util_Constant
 * Method:    commonKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ebeijia_util_Constant_commonKey
  (JNIEnv *, jclass);

/*
 * Class:     com_android_ebeijia_util_Constant
 * Method:    mrchNo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ebeijia_util_Constant_mrchNo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
